wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000 #找了好久的bug... 我吐了.... 这个是要写成前端的3000才可以

# \u4E0D\u884C\u5C31\u8BD5\u8BD58160
